const businesses = [
  {
    id: "royal-oak-qr",
    name: "The Royal Oak",
    phone: "01904 848777",
    category: "Pub / restaurant",
    area: "Goodramgate",
    priority: "High",
    score: 4,
    art: "pub",
    icon: "🍺",
    insight: "Gold-highlighted QR prospect. York branch at 18 Goodramgate, YO1 7LG.",
    weaknesses: ["Check table service", "Food/drink table orders", "Bar pressure"],
    pitch: "QR ordering could help with food and drink orders from tables and reduce pressure at the bar."
  },
  {
    id: "lucia-york-qr",
    name: "Lucia York",
    phone: "01904 731599",
    category: "Restaurant / cocktail bar",
    area: "Swinegate Court East",
    priority: "High",
    score: 4,
    art: "pub",
    icon: "🍸",
    insight: "Gold-highlighted QR prospect. Busy restaurant/cocktail setup with strong repeat-drink potential.",
    weaknesses: ["Drink reorders", "Dessert upsells", "Allergen notes"],
    pitch: "Pitch fast drink reorders, desserts and allergen notes from the table."
  },
  {
    id: "cut-craft-york-qr",
    name: "The Cut & Craft York",
    phone: "01904 593500",
    category: "Restaurant / cocktail bar",
    area: "St Sampson's Square",
    priority: "High",
    score: 3,
    art: "restaurant",
    icon: "🥩",
    insight: "Gold-highlighted QR prospect. Large steak/cocktail restaurant at 8 St Sampson's Square, YO1 8RN.",
    weaknesses: ["Drinks reorders", "Sides and sauces", "Dessert upsells"],
    pitch: "Large venue, good for table ordering, drinks reorders, brunch/lunch and dessert upsells."
  },
  {
    id: "impossible-york-qr",
    name: "Impossible York",
    phone: "07767 326146",
    category: "Restaurant / bar / events",
    area: "St Helen's Square",
    priority: "High",
    score: 3,
    art: "pub",
    icon: "🎉",
    insight: "Gold-highlighted QR prospect. Large restaurant/bar/events venue at 3 St Helen's Square, YO1 8QN.",
    weaknesses: ["Events ordering", "Group dining", "Drinks queues"],
    pitch: "Pitch QR ordering for events, group dining and drinks ordering."
  },
  {
    id: "york-minster-refectory-qr",
    name: "York Minster Refectory",
    phone: "01904 307399",
    category: "Restaurant / café / bar",
    area: "Deangate",
    priority: "High",
    score: 3,
    art: "cafe",
    icon: "☕",
    insight: "Gold-highlighted QR prospect. Tourist-heavy all-day venue at 2 Deangate, YO1 7JA.",
    weaknesses: ["Coffee/lunch queues", "Tourist groups", "All-day ordering"],
    pitch: "Pitch faster ordering for coffee, lunch, dinner, drinks and add-ons."
  },
  {
    id: "brew-york-yuzu-qr",
    name: "Brew York Walmgate / YUZU",
    phone: "01904 848448",
    category: "Taproom / beer hall / food",
    area: "Walmgate",
    priority: "High",
    score: 3,
    art: "pub",
    icon: "🍻",
    insight: "Gold-highlighted QR prospect. Very large venue with 350+ seats across multiple areas.",
    weaknesses: ["Check existing QR system", "Multiple seating areas", "Food and drink orders"],
    pitch: "Strong pitch for table food/drink ordering, but first check if they already use OrderTab or QR ordering."
  },
  {
    id: "old-liquor-store-qr",
    name: "The Old Liquor Store",
    phone: "01904 950147",
    category: "Restaurant / bar",
    area: "Bishopthorpe Road",
    priority: "High",
    score: 4,
    art: "pub",
    icon: "🍷",
    insight: "Gold-highlighted QR prospect. Racecourse and group-dining angle at Bishopthorpe Road, YO23 1FT.",
    weaknesses: ["Race day groups", "Brunch ordering", "Table drinks"],
    pitch: "Pitch QR ordering for race days, brunch, table drinks and group tabs."
  },
  {
    id: "cresci-pizzeria-qr",
    name: "Cresci Pizzeria",
    phone: "01904 639395",
    category: "Pizzeria / restaurant",
    area: "Piccadilly",
    priority: "Medium",
    score: 5,
    art: "restaurant",
    icon: "🍕",
    insight: "Gold-highlighted QR prospect. 20 Piccadilly, YO1 9NU. Already digital-friendly, so check fit first.",
    weaknesses: ["Check current system", "Drinks/sides", "Group orders"],
    pitch: "QR table ordering could still help with drinks, sides, desserts and group orders."
  },
  {
    id: "star-inn-city-qr",
    name: "The Star Inn The City",
    phone: "01904 619208",
    category: "Restaurant",
    area: "Museum Street",
    priority: "Medium",
    score: 6,
    art: "restaurant",
    icon: "🍽️",
    insight: "Gold-highlighted QR prospect. Premium venue at Lendal Engine House, Museum Street, YO1 7DR.",
    weaknesses: ["Premium service fit", "Drinks/add-ons only", "Careful pitch"],
    pitch: "Pitch QR as optional drinks/add-ons support, not replacing waiter service."
  },
  {
    id: "mannion-co-york-qr",
    name: "Mannion & Co York",
    phone: "01904 631030",
    category: "Café / bistro / deli",
    area: "Blake Street",
    priority: "High",
    score: 4,
    art: "cafe",
    icon: "☕",
    insight: "Gold-highlighted QR prospect. Busy first-come-first-served café/bistro at 1 Blake Street, YO1 8QJ.",
    weaknesses: ["Queue pressure", "Repeat drinks", "Add-ons"],
    pitch: "Pitch QR ordering to reduce queue pressure and speed repeat drinks/add-ons."
  },
  {
    id: "merchants-coffee-house-qr",
    name: "Merchants' Coffee House",
    phone: "01904 654818",
    category: "Café",
    area: "Fossgate",
    priority: "Medium",
    score: 5,
    art: "cafe",
    icon: "☕",
    insight: "Gold-highlighted QR prospect. Fossgate, YO1 9XD, with indoor/outdoor seating.",
    weaknesses: ["Check queue pressure", "Outdoor seating", "Tourist setting"],
    pitch: "Pitch QR ordering if they have queues or table service pressure."
  },
  {
    id: "whippet-inn-qr",
    name: "The Whippet Inn",
    phone: "01904 500660",
    category: "Restaurant / steakhouse / pub-restaurant",
    area: "North Street",
    priority: "High",
    score: 4,
    art: "restaurant",
    icon: "🥩",
    insight: "Gold-highlighted QR prospect. Restaurant/bar setup at 15 North Street, YO1 6JD.",
    weaknesses: ["Drinks", "Steak add-ons", "Group meals"],
    pitch: "Table ordering could help with drinks, sides, steak add-ons, desserts and group meals."
  },
  {
    id: "cosy-club-york-qr",
    name: "Cosy Club York",
    phone: "01904 395056",
    category: "Large restaurant / café-bar",
    area: "Fossgate",
    priority: "High",
    score: 3,
    art: "pub",
    icon: "🍹",
    insight: "Gold-highlighted QR prospect. Large all-day dining venue at 19-22 Fossgate, YO1 9TA.",
    weaknesses: ["Brunch extras", "Cocktail reorders", "Private dining"],
    pitch: "Strong QR angle for drinks, brunch extras, groups and repeat orders."
  },
  {
    id: "bow-room-grays-court-qr",
    name: "The Bow Room at Grays Court",
    phone: "01904 612613",
    category: "Fine dining restaurant / hotel restaurant",
    area: "Chapter House Street",
    priority: "Medium",
    score: 6,
    art: "restaurant",
    icon: "🍽️",
    insight: "Gold-highlighted QR prospect. Premium hotel restaurant at Grays Court Hotel, YO1 7JH.",
    weaknesses: ["Private dining", "Dietary notes", "Event pre-orders"],
    pitch: "Pitch QR for private dining, wine/drinks, dietary notes and event pre-orders rather than full table self-ordering."
  },
  {
    id: "judges-lodging-qr",
    name: "The Judge’s Lodging",
    phone: "01904 638733",
    category: "Restaurant / pub dining / hotel",
    area: "Lendal",
    priority: "High",
    score: 4,
    art: "pub",
    icon: "🍺",
    insight: "Gold-highlighted QR prospect. Food/drink venue at 9 Lendal, YO1 8AQ.",
    weaknesses: ["Lunch orders", "Group tables", "Private dining"],
    pitch: "QR could help lunches, drinks, group tables and event/private dining orders."
  },
  {
    id: "kennedys-bar-restaurant-qr",
    name: "Kennedy’s Bar & Restaurant",
    phone: "01904 620222",
    category: "Restaurant / bar",
    area: "Little Stonegate",
    priority: "High",
    score: 4,
    art: "pub",
    icon: "🍔",
    insight: "Gold-highlighted QR prospect. Lively food/drink venue at 1 Little Stonegate, YO1 8AX.",
    weaknesses: ["BBQ orders", "Group dining", "Table reorders"],
    pitch: "QR could boost drinks, loaded plates, snacks and table reorders."
  },
  {
    id: "oshibi-korean-bistro-qr",
    name: "Oshibi Korean Bistro",
    category: "Korean restaurant",
    area: "York",
    priority: "Medium",
    score: 5,
    art: "restaurant",
    icon: "🍜",
    insight: "Gold-highlighted QR prospect. Add as medium priority until table count/capacity is confirmed.",
    weaknesses: ["Check seating size", "Allergy notes", "Group orders"],
    pitch: "QR could support table food orders, allergy notes, drinks and group orders if seating is large enough."
  }
];
