const businesses = [
  {
    id: 'shambles-kitchen',
    name: 'Shambles Kitchen',
    category: 'Food',
    area: 'Shambles',
    priority: 'Medium',
    score: 6,
    art: 'food',
    icon: '🥪',
    maps: 'https://www.google.com/maps/search/?api=1&query=Shambles%20Kitchen%20York%20reviews',
    insight: 'Busy food spot near tourist traffic. Check whether owner photos, menu shots and review replies look strong compared with nearby food places.',
    weaknesses: ['Check if the main photo is clean and appetising', 'Check whether recent reviews get replies', 'Check if menu and best sellers are obvious'],
    pitch: 'We can make your Google listing easier for tourists to trust before they arrive — better photo order, review replies and a simple QR review system.'
  },
  {
    id: 'parlormade',
    name: 'Parlormade Café & Scone House',
    category: 'Café',
    area: 'Shambles',
    priority: 'Medium',
    score: 6,
    art: 'cafe',
    icon: '☕',
    maps: 'https://www.google.com/maps/search/?api=1&query=Parlormade%20Cafe%20and%20Scone%20House%20York%20reviews',
    insight: 'Tourist-friendly café where photos matter a lot. Useful target if the listing lacks clean food shots, updated opening info or fresh review replies.',
    weaknesses: ['Look for dark food photos', 'Check recent review replies', 'Check if the description sells the tourist experience'],
    pitch: 'I can help make your Google profile look more inviting to people walking around Shambles and searching for cafés nearby.'
  },
  {
    id: 'shambles-tavern',
    name: 'Shambles Tavern',
    category: 'Pub',
    area: 'Shambles Market',
    priority: 'Medium',
    score: 5,
    art: 'pub',
    icon: '🍺',
    maps: 'https://www.google.com/maps/search/?api=1&query=Shambles%20Tavern%20York%20reviews',
    insight: 'Pubs can win customers from atmosphere photos and review replies. Check if the listing quickly shows the vibe on mobile.',
    weaknesses: ['Check atmosphere photos', 'Check if opening hours are clear', 'Check replies to lower reviews'],
    pitch: 'I can improve how your pub looks on Maps so tourists quickly see the atmosphere, food and drink offer and why they should choose you.'
  },
  {
    id: 'hebden-tea',
    name: 'Hebden Tea Shambles',
    category: 'Retail',
    area: 'Shambles',
    priority: 'High',
    score: 4,
    art: 'retail',
    icon: '🫖',
    maps: 'https://www.google.com/maps/search/?api=1&query=Hebden%20Tea%20Shambles%20York%20reviews',
    insight: 'Product-based shop. Good target because Google product photos, descriptions and categories can directly show what they sell.',
    weaknesses: ['Check product photos', 'Check if best sellers are visible', 'Check whether listing explains what makes them different'],
    pitch: 'I can make your Google listing show your best products more clearly and help tourists understand what you sell before they walk in.'
  },
  {
    id: 'ipsofacto-art',
    name: 'Ipsofacto Art',
    category: 'Retail',
    area: 'Shambles / Market area',
    priority: 'High',
    score: 4,
    art: 'art',
    icon: '🎨',
    maps: 'https://www.google.com/maps/search/?api=1&query=Ipsofacto%20Art%20York%20reviews',
    insight: 'Small niche/art business. Very good type of target because owner photos, product display and description can often be improved quickly.',
    weaknesses: ['Check if photos show products clearly', 'Check review count', 'Check if description explains the shop'],
    pitch: 'I help small York shops look more professional on Google Maps with better photo order, clearer wording and a review QR card.'
  },
  {
    id: 'ambient-company',
    name: 'The Ambient Company',
    category: 'Retail',
    area: 'Shambles Market',
    priority: 'High',
    score: 4,
    art: 'retail',
    icon: '🛍️',
    maps: 'https://www.google.com/maps/search/?api=1&query=The%20Ambient%20Company%20York%20reviews',
    insight: 'Market/retail style lead. Stalls and smaller shops often have less polished Google Maps branding.',
    weaknesses: ['Check if business has enough photos', 'Check if opening times are clear', 'Check if product type is obvious'],
    pitch: 'I can help make your listing easier to find and understand, especially for tourists using Google Maps around Shambles Market.'
  },
  {
    id: 'moo-york-deli',
    name: 'Moo York Deli',
    category: 'Food',
    area: 'Shambles Market',
    priority: 'High',
    score: 4,
    art: 'food',
    icon: '🥙',
    maps: 'https://www.google.com/maps/search/?api=1&query=Moo%20York%20Deli%20Shambles%20Market%20reviews',
    insight: 'Food stall/deli type business. Great audit target if food photos are dark, old or mostly uploaded by customers.',
    weaknesses: ['Check main photo', 'Check menu/product shots', 'Check number of owner-uploaded photos'],
    pitch: 'I can make your food look better on Google Maps so people choose you while walking around the market.'
  },
  {
    id: 'crumbles-desserts',
    name: 'Crumbles Desserts',
    category: 'Food',
    area: 'Shambles Market',
    priority: 'High',
    score: 4,
    art: 'dessert',
    icon: '🍰',
    maps: 'https://www.google.com/maps/search/?api=1&query=Crumbles%20Desserts%20York%20reviews',
    insight: 'Dessert businesses are perfect for visual Google upgrades. Strong photos and review requests can make a big difference.',
    weaknesses: ['Check dessert close-ups', 'Check review replies', 'Check if location is easy to understand'],
    pitch: 'Your desserts are visual, so Google Maps photos matter. I can help your listing look cleaner and more tempting.'
  },
  {
    id: 'mo-the-barber',
    name: 'Mo The Barber',
    category: 'Barber',
    area: 'Coppergate / city centre',
    priority: 'High',
    score: 4,
    art: 'barber',
    icon: '✂️',
    maps: 'https://www.google.com/maps/search/?api=1&query=Mo%20The%20Barber%20York%20reviews',
    insight: 'Barbers are strong targets because people search locally and compare photos/reviews fast. Before/after haircut photos can sell the service.',
    weaknesses: ['Check haircut photo quality', 'Check review replies', 'Check services/prices visibility'],
    pitch: 'I can make your barber listing look sharper with better service wording, photo order and a simple review QR system.'
  },
  {
    id: 'kiosk-coffee',
    name: 'Kiosk Coffee',
    category: 'Café',
    area: 'Fossgate',
    priority: 'Medium',
    score: 5,
    art: 'cafe',
    icon: '☕',
    maps: 'https://www.google.com/maps/search/?api=1&query=Kiosk%20Coffee%20York%20reviews',
    insight: 'Smaller café lead. Check if Google photos show the front clearly and whether reviews are being replied to.',
    weaknesses: ['Check front-of-shop photo', 'Check drink/food photos', 'Check if profile looks active'],
    pitch: 'I can help make your café easier to choose on Google Maps with cleaner photos, better wording and review replies.'
  },
  {
    id: 'shop-not-named',
    name: 'The Shop That Must Not Be Named',
    category: 'Tourist shop',
    area: 'Shambles',
    priority: 'Low',
    score: 7,
    art: 'gift',
    icon: '🎁',
    maps: 'https://www.google.com/maps/search/?api=1&query=The%20Shop%20That%20Must%20Not%20Be%20Named%20York%20reviews',
    insight: 'Popular themed shop. It may already have strong branding, so only approach if you find weak photo order, no review replies or missing product info.',
    weaknesses: ['Check if profile already looks polished', 'Check product photos', 'Check review response activity'],
    pitch: 'I noticed your shop gets lots of visitor attention. I can help keep the Google listing looking as polished as the shop itself.'
  },
  {
    id: 'potions-cauldron',
    name: 'The Potions Cauldron',
    category: 'Tourist shop',
    area: 'Shambles',
    priority: 'Low',
    score: 7,
    art: 'gift',
    icon: '🧪',
    maps: 'https://www.google.com/maps/search/?api=1&query=The%20Potions%20Cauldron%20York%20reviews',
    insight: 'Themed visitor shop. Audit it carefully because bigger tourist brands may already have decent photos and profile management.',
    weaknesses: ['Check latest visitor photos', 'Check products tab', 'Check if posts or updates exist'],
    pitch: 'I can help turn your Google listing into a stronger visitor preview with clean photos, product highlights and better review replies.'
  }
];
