(() => {
  const services = [
    { title: 'Better Google photos', short: 'Make the first impression look cleaner and more inviting.', detail: 'We help choose stronger cover photos, tidy the order of existing images, and plan fresh shop-front, product, food, team, or interior photos so people immediately understand what you offer.', includes: ['Photo order cleanup', 'Better cover image choice', 'Simple shot list for new photos'] },
    { title: 'Google listing cleanup', short: 'Make your profile easier to trust and understand.', detail: 'We check the important parts of the Google listing: business description, categories, opening times, services, links, and small details that can confuse customers before they visit.', includes: ['Description and service wording', 'Category and detail check', 'Opening hours and links review'] },
    { title: 'Review QR code', short: 'Make it easier for happy customers to leave reviews.', detail: 'We create a simple review link and QR code that can be used at the counter, on receipts, on a small card, or sent by message after a good customer experience.', includes: ['Review link setup', 'QR code design', 'Simple staff explanation'] },
    { title: 'Website or landing page', short: 'Give customers a simple place to see what you do.', detail: 'For shops without a clear website, we can make a simple page that shows your offer, photos, opening times, contact details, and links back to your Google profile.', includes: ['Clean mobile page', 'Contact and opening info', 'Google listing links'] },
    { title: 'Social media links', short: 'Connect your Instagram, Facebook, or website clearly.', detail: 'We make sure customers can move between your Google listing, social pages, website, and contact options without getting lost or landing on outdated links.', includes: ['Link check', 'Profile connection', 'Simple customer path'] },
    { title: 'Full digital refresh', short: 'A tidy upgrade across Google, web, reviews, and links.', detail: 'This is the full cleanup for businesses that want their online presence to feel more professional without making it complicated or corporate.', includes: ['Google listing refresh', 'Photos and wording', 'Review and link setup'] }
  ];
  function ensurePage(){let page=document.querySelector('#shopPage');if(page)return page;page=document.createElement('section');page.id='shopPage';page.className='shop-page';page.innerHTML='<div class="shop-page-head"><button id="shopBackBtn">‹</button><div><strong>Shop</strong><span>Client service menu</span></div></div><div id="shopPageContent" class="shop-page-content"></div>';document.body.appendChild(page);page.querySelector('#shopBackBtn').onclick=closeShop;return page;}
  function serviceCard(s,i){return `<button class="shop-service-card" data-i="${i}"><span>0${i+1}</span><strong>${s.title}</strong><small>${s.short}</small><em>Tap for details</em><div class="shop-service-detail"><p>${s.detail}</p><ul>${s.includes.map(x=>`<li>${x}</li>`).join('')}</ul></div></button>`;}
  function openShop(){const page=ensurePage(),content=page.querySelector('#shopPageContent');content.innerHTML=`<div class="shop-hero"><span>Google Maps Upgrade</span><h1>What would you like help with?</h1><p>Pick a service to see a simple explanation. Clear options, calm wording, and practical help for your shop.</p></div><div class="shop-service-grid">${services.map(serviceCard).join('')}</div><div class="shop-footer-note">We can keep this small and practical, or do a full refresh if you want everything tidied up together.</div>`;page.classList.add('open');document.querySelector('#sideMenu')?.classList.remove('open');document.querySelector('#menuBackdrop')?.classList.remove('open');content.querySelectorAll('.shop-service-card').forEach(card=>card.onclick=()=>card.classList.toggle('open'));}
  function closeShop(){document.querySelector('#shopPage')?.classList.remove('open');document.querySelector('#menuBtn')?.click();}
  document.addEventListener('click',e=>{const btn=e.target.closest?.('.menu-item[data-section="shop"]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();openShop();},true);
  window.ShopPage={open:openShop};
})();
