(() => {
  const services = [
    { title: 'Google listing and photos', short: 'Make your Google profile clearer, cleaner, and easier to trust.', detail: 'We improve the first impression of your Google listing by checking the wording, categories, opening details, links, and photo order. The goal is simple: help customers understand your shop quickly and feel more confident visiting.', includes: ['Photo order and cover image cleanup', 'Description and service wording', 'Opening hours, links, and key details check'] },
    { title: 'Review QR code', short: 'Make it easier for happy customers to leave reviews.', detail: 'We create a simple review link and QR code that can be used at the counter, on receipts, on a small card, or sent by message after a good customer experience.', includes: ['Review link setup', 'QR code design', 'Simple staff explanation'] },
    { title: 'Website or landing page', short: 'Give customers a simple place to see what you do.', detail: 'For shops without a clear website, we can make a simple page that shows your offer, photos, opening times, contact details, and links back to your Google profile.', includes: ['Clean mobile page', 'Contact and opening info', 'Google listing links'] }
  ];
  function ensurePage(){let page=document.querySelector('#shopPage');if(page)return page;page=document.createElement('section');page.id='shopPage';page.className='shop-page';page.innerHTML='<div class="shop-page-head"><button id="shopBackBtn">‹</button><div><strong>Shop</strong><span>Client service menu</span></div></div><div id="shopPageContent" class="shop-page-content"></div>';document.body.appendChild(page);page.querySelector('#shopBackBtn').onclick=closeShop;return page;}
  function serviceCard(s,i){return `<button class="shop-service-card" data-i="${i}"><span>0${i+1}</span><strong>${s.title}</strong><small>${s.short}</small><em>Tap for details</em><div class="shop-service-detail"><p>${s.detail}</p><ul>${s.includes.map(x=>`<li>${x}</li>`).join('')}</ul></div></button>`;}
  function openShop(){const page=ensurePage(),content=page.querySelector('#shopPageContent');content.innerHTML=`<div class="shop-hero"><span>Google Maps Upgrade</span><h1>What would you like help with?</h1><p>Pick a service to see a simple explanation. Clear options, calm wording, and practical help for your shop.</p></div><div class="shop-service-grid">${services.map(serviceCard).join('')}</div><div class="shop-footer-note">We can keep this small and practical, focused only on what your shop actually needs.</div>`;page.classList.add('open');document.querySelector('#sideMenu')?.classList.remove('open');document.querySelector('#menuBackdrop')?.classList.remove('open');content.querySelectorAll('.shop-service-card').forEach(card=>card.onclick=()=>card.classList.toggle('open'));}
  function closeShop(){document.querySelector('#shopPage')?.classList.remove('open');document.querySelector('#menuBtn')?.click();}
  document.addEventListener('click',e=>{const btn=e.target.closest?.('.menu-item[data-section="shop"]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();openShop();},true);
  window.ShopPage={open:openShop};
})();
